### ISSUE TITLE
Logo Needed!!

### ISSUE THREAD

**Issue by jasonwynn10** [LostTeam/LostCore#1]
Can someone make a logo for the LostCore Plugin?
@LostTeam/pocketmine-plugin-programmers

**Comment by TheDeibo** [comment]
![lostcorelogo](https://cloud.githubusercontent.com/assets/10010369/19316153/41797da2-9098-11e6-9425-d74b5578156d.png) How about this?

**Comment by TheDeibo** [comment]
![lostcorelogo1](https://cloud.githubusercontent.com/assets/10010369/19317101/d220c3da-909b-11e6-86ba-8ba687c81c3a.png)

**Comment by TheDeibo** [comment]
![lostcorelogo2](https://cloud.githubusercontent.com/assets/10010369/19317972/b3aacf2e-909e-11e6-8ce3-8c73ad012a73.png)

**Comment by jasonwynn10** [comment]
Sweet, but I need something that's 1040 x 388 pixels

**Comment by TheDeibo** [comment]
DO you want it like above, but with the size?

**Comment by jasonwynn10** [comment]
if you can, that'd be great.

**Comment by TheDeibo** [comment]
# Here you are. 1040px x 388px

![logo banner](https://cloud.githubusercontent.com/assets/10010369/19327437/f53c2bcc-90c6-11e6-99b9-25fa18cf8294.png)

**Comment by jasonwynn10** [comment]
That looks awesome! Thanks!

**Comment by MCUnderground** [comment]
👍

**Comment by TheDeibo** [comment]
Ha. Only just noticed the squiggly lines on the edge of the image. Never mind. I added that effect by accident. It still looks good though.

**Comment by jasonwynn10** [comment]
XD
